vim.o["number"]         = true -- show line numbers
vim.o["relativenumber"] = true -- show relative line numbers
vim.o["list"]           = true -- show invisible characters
vim.o["listchars"]      = "tab:»·,trail:·,nbsp:·,extends:»,precedes:«"
vim.o["expandtab"]      = true -- use spaces instead of tabs
vim.o["tabstop"]        = 4 -- number of visual spaces per TAB
vim.o["shiftwidth"]     = 4 -- number of spaces to use for autoindent
vim.o["smarttab"]       = true
vim.o["wrap"]           = true -- wrap lines
vim.o["showbreak"]      = "↪" -- "↳"
vim.o["laststatus"]     = 2 -- always show status line
vim.o["display"]        = "lastline" -- show last line of file
vim.o["clipboard"]      = "unnamedplus" -- copy to system clipboard
vim.o["mouse"]          = "a" -- enable mouse in all modes
vim.o["wildignore"]     = ".git,.hg,.svn,*.pyc,*.o,*.out,*.jpg,*.jpeg,*.png,*.gif,*.zip,**/tmp/**,*.DS_Store,**/node_modules/**,**/bower_modules/**"
vim.o["backup"]         = false -- disable backup
vim.o["writebackup"]    = false -- don't create backup files
vim.o["swapfile"]       = false -- disable swap file
vim.o["undofile"]       = true -- enable persistent undo
--vim.o["undodir"]        = global.cache_dir .. "undo/" -- set undo directory
vim.o["cursorline"]     = true -- highlight current line
vim.o["cursorcolumn"]   = false -- highlight current column
vim.o["virtualedit"]    = "all" -- allow cursor to move in virtual space
-- vim.o["guifont"]        = "Source Code Pro:h14" -- font for gui
vim.opt.guifont         = { "JetBrainsMono Nerd Font", ":h14" }
vim.o["fileformat"]     = "unix" -- always use unix line endings (LF)
vim.o["spelllang"]      = "en_us,cjk" -- set spell check language
vim.o["spell"]          = true -- enable spell checking
vim.o["scrolloff"]      = 8 -- lines of content to keep above and below cursor
vim.o["autoread"]       = true -- automatically reload files when changed
vim.cmd("au FocusGained * :checktime")
vim.o["autowrite"]      = true -- automatically save before commands like :next and :make
vim.o["cmdheight"]      = 1 -- height of command bar
vim.o["termguicolors"]  = true -- enable 24-bit RGB colors
vim.o["conceallevel"]   = 0
vim.o["foldlevelstart"] = 99
vim.o["foldenable"]     = true
vim.o["errorbells"]     = true
vim.o["visualbell"]     = true
vim.o["hidden"]         = true
vim.o["magic"]          = true -- make regular
vim.o["encoding"]       = "utf-8"
--vim.o["viewoptions"]    = "folds,cursor,curdir,slash, unix"
-- vim.o["sessionop"]      = "curdir,help, tabpages, winsize"
vim.o["wildignorecase"] = true
vim.o["wildignore"]     = ".git,.hg,.svn,*.pyc,*.o,*.out,*.jpg,*.jpeg,*.png,*.gif,*.zip,**/tmp/**,*.DS_Store,**/node_modules/**,**/bower_modules/**"
vim.o['signcolumn']     = "yes"
vim.cmd("colorscheme catppuccin")
